ALTER TABLE alerts ADD COLUMN IF NOT EXISTS current_source VARCHAR;
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS current_as_of_date DATE;
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS current_fetched_at TIMESTAMPTZ;
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS current_expires_at TIMESTAMPTZ;
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS current_stale BOOLEAN;
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS current_confidence NUMERIC;
